# Generated by Django 3.2.4 on 2021-06-30 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_note_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watering', models.DateField()),
                ('note', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.note')),
                ('user', models.ManyToManyField(related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
