# Generated by Django 3.2.4 on 2021-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='note',
        ),
        migrations.AddField(
            model_name='bookmark',
            name='note',
            field=models.ManyToManyField(related_name='bookmarks', to='main.Note'),
        ),
    ]
