# Generated by Django 3.2.4 on 2021-06-30 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210630_2055'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
