# Generated by Django 3.2.4 on 2021-06-30 18:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_delete_bookmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('last_watering', models.DateField()),
                ('user', models.ManyToManyField(related_name='bookmarks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
