# Generated by Django 3.2.4 on 2021-06-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='last_watering',
            field=models.DateField(blank=True),
        ),
    ]
