# Generated by Django 3.2.4 on 2021-06-30 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_bookmark_last_watering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='last_watering',
            field=models.DateField(blank=True, null=True),
        ),
    ]
