# Generated by Django 3.2.4 on 2021-07-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_bookmark_last_watering'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='photo',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
