# Generated by Django 3.2.4 on 2021-07-04 10:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_note_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='photo',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('user', models.ManyToManyField(related_name='code', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
