# Generated by Django 3.2.5 on 2021-07-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210704_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='watering_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
