# Generated by Django 3.2.5 on 2021-07-14 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_note_watering_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='last_fertilize',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='fertilize_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
