# Generated by Django 3.2.5 on 2021-07-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_sitestatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitestatistics',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
